#!/bin/bash
# Put this script in your $HOME/.local/bin folder
# if "off" is given as parameter, then spawn a new thread to turn off the screen
[ "$1" = "off" ] && $(sleep 5 && xset dpms force off) &

# this must be the last command, and it must be 'non forking', as expected by 'xautolock'
i3lockmore -d --lock-icon --image-fill $HOME/Documents/wallpaper/horse.jpg
